### ISSUE TITLE
After selecting "Permanent" from Peter Lowe's Ad tracking block, an ad popped up that I can't get rid of

### ISSUE THREAD

**Issue by TubbyLady** [uBlockOrigin/uAssets#12339]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

https://www.yahoo.com/subscriptions/products/nordvpn?ncid=adb_306774524_327361_135562_dG9wLW9mLW1lc3NhZ2U_0#section-features3

### Category

Popup AD will not go away after selecting "permanent" from the notification by Peter Lowe's Ad Tracking.

### Describe the issue

I wrote to the White House and they responded with a form response.  However, BEFORE I could read their standard response to make sure it is the usual one. One of the notices from Peter Lowe's Ad Tracking appeared, saying the site was blocked!  Ridiculous! This was a message from the White House.  You know, the President of the United States.  So, knowing I write to the White House all the time, I selected "permanent" to UNblock it, so I don't have go through the block each time. UNFORTUNATELY , now an AD from Yahoo/NordVPN appears and I can't make it go away. How do I block this ad? 
URL that popped up and won't go away.
https://www.yahoo.com/subscriptions/products/nordvpn?ncid=adb_306774524_327361_135562_dG9wLW9mLW1lc3NhZ2U_0#section-features3

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<!-- drag-and-drop screenshot here --
![Yahoo NordVPN ad screen shot](https://user-images.githubusercontent.com/101950439/159139012-ff0414c2-0ba3-4116-ae6c-4eb86f96b210.png)
>

</details>

### Configuration

I don't know what you mean.

**Comment by mapx-** [comment]
We need clear steps to reproduce your issue, we are not interested to whom you wrote.
1. go to example.com
2. write whatever you want
3. click x button
4. I got this ad (screenshot)

and so on

Then, go into dashboard, support tab, post here: `Troubleshooting Information`
