### ISSUE TITLE
tracking.clck2trck.com: privacy

### ISSUE THREAD

**Issue by big-cat-loaf** [uBlockOrigin/uAssets#13668]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://tracking.clck2trck.com/`
`https://tracking.clck2trck.com/aff_c?offer_id=385&aff_id=6300&source=3730`

### Category

privacy

### Describe the issue

IT has tracking in there Name  and is a fake link a found on Youtbe like  on this channal.  
`https://www.youtube.com/c/Sozemain/about?app=desktop&openChannelReportingDialog=1` 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.42.4
Chromium: 102
filterset (summary): 
  network: 375928
  cosmetic: 318880
  scriptlet: 40520
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://abl.arapurayil.com/filters/main.txt: 148306-2, 16h.39m
    https://filters.adtidy.org/extension/ublock/filters/6_optimized.txt: 5540-128, 17h.59m
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/firewall/spy.txt: 167-0, 3d.19h.42m
    https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Austria.txt: 24115-28, 3d.19h.40m
    https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt: 6143-72, 1d.19h.25m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-92, 1d.19h.22m
    https://winhelp2002.mvps.org/hosts.txt: 8730-1647, 3d.19h.37m
    ALB-0: 267-2, 16h.49m
    BGR-0: 1116-13, 3d.19h.39m
    CHN-0: 29118-7178, 17h.54m
    CZE-0: 710-4, 16h.44m
    EST-0: 450-2, 16h.45m
    FIN-0: 1799-1, 18h.4m
    FRA-0: 28869-6006, 17h.53m
    GRC-0: 1002-3, 1d.21h.15m
    HUN-0: 2144-22, 16h.48m
    IDN-0: 8931-50, 18h.6m
    IND-0: 10651-2, 16h.34m
    IRN-0: 1344-18, 17h.52m
    ISL-0: 193-1, 3d.19h.38m
    [35 lists not shown]: [too many]
  default: 
    user-filters: 80-0, never
    DEU-0: 5808-2580, 19h.51m
    easylist: 68167-16115, 17h.49m
    easyprivacy: 27182-14911, 17h.48m
    plowe-0: 3670-3005, 8d.20h.10m
    ublock-abuse: 75-59, 8d.20h.8m
    ublock-badware: 4191-722, 17h.47m
    ublock-filters: 31820-4206, 16h.51m
    ublock-privacy: 222-82, 8d.20h.4m
    ublock-quick-fixes: 210-16, 16h.36m
    ublock-unbreak: 1798-132, 16h.50m
    urlhaus-1: 7336-837, 16h.35m
filterset (user): [array of 80 redacted]
trustedset: 
  added: [array of 3 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  added: [array of 23 redacted]
hostRuleset: 
  added: [array of 15 redacted]
urlRuleset: 
  added: [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1036 ms (selfie)
  maxAssetCacheWait: 959 ms
popupPanel: 
  blocked: 0
  no-cosmetic-filtering: true
  no-large-media: true
  no-popups: true
  no-remote-fonts: true
  no-scripting: true
```
</details>

**Comment by mapx-** [comment]
- reset uBO to default settings, don't add other (or all) lists
- try to explain intelligibly what is not ok

**Comment by MasterKia** [comment]
> ```yaml
>  added: 
>     ALB-0: 267-2, 16h.49m
>     BGR-0: 1116-13, 3d.19h.39m
>     CHN-0: 29118-7178, 17h.54m
>     CZE-0: 710-4, 16h.44m
>     EST-0: 450-2, 16h.45m
>     FIN-0: 1799-1, 18h.4m
>     FRA-0: 28869-6006, 17h.53m
>     GRC-0: 1002-3, 1d.21h.15m
>     HUN-0: 2144-22, 16h.48m
>     IDN-0: 8931-50, 18h.6m
>     IND-0: 10651-2, 16h.34m
>     IRN-0: 1344-18, 17h.52m
>     ISL-0: 193-1, 3d.19h.38m
>     [35 lists not shown]: [too many]
> ```


@big-cat-loaf Why enable all those regional lists?
