### ISSUE TITLE
uBO doesn't block all tracking links on youtube

### ISSUE THREAD

**Issue by githubissocool** [uBlockOrigin/uAssets#15276]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

So while i was watching a youtube video i did some debugging just to see what uBO does and i notice that a tracking link from youtube isnt blocked.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/97558900/195970773-ad0c37a7-316b-44b3-95d4-16c6cbba441b.png">

### A specific URL where the issue occurs.

https://www.youtube.com/watch?v=hiust_1qDH8

### Steps to Reproduce

i am not good at giving steps to reproduce but i guess i will do it anyways

check if the tracking link is supposed to be blocked in the filter lists

if not then ask the person maintaining the list to fix it

update uBO to use the fixed list

### Expected behavior

The tracking link to be blocked

### Actual behavior

Tracking link isnt blocked

### uBO version

 1.44.4

### Browser name and version

Chromium 106.0.5249.119 (Official Build) (64-bit) (cohort: Stable) 

### Operating System and version

Windows 11 Version 21H2 (Build 22000.1098)

**Comment by gwarser** [comment]
https://github.com/easylist/easylist/commit/535dbbffbdc9d5e0666d05d1ee1c795164e59709

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/195972940-4f99c8d0-ec6b-41cd-acb2-270992dc6ca2.png)

**Comment by gwarser** [comment]
This filter has at least 10 years of history. Check your uBO is working properly and all default filters are enabled.

**Comment by gwarser** [comment]
This is on Chrome, can be caused by prefetching, but I cannot reproduce.
