### ISSUE TITLE
[NSFW] adultempire.com: tracking

### ISSUE THREAD

**Issue by Sonic5435325** [uBlockOrigin/uAssets#18023]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Tracker
`analytics.adultempire.com`

analytics.adultempire.com/js/container_iXaVs8DZ.js (Says "Matomo - free/libre analytics platform" at the top)

Rejected/dismissed by EasyList/EasyPrivacy for some reason (Even though it uses Matomo's tracking code):
https://github.com/easylist/easylist/issues/15765

### URL(s) where the issue occurs.

`https://www.adultempire.com/`

### uBO version

uBlock Origin v1.49.3b9

### Browser name and version

Firefox 112.0.2

### Settings

- Custom filter lists

**Comment by gorhill** [comment]
https://github.com/easylist/easylist/issues/15765#issuecomment-1540995746

I don't see anything in the logger which raise concerns, I will trust EasyPrivacy's decision.

**Comment by stephenhawk8054** [comment]
I'm also not clear about EP's answer. These 2 are basically the same code 

```
https://analytics.adultempire.com/js/container_iXaVs8DZ.js
https://matomo.shopclues.com/js/container_xxcPN3Is.js
``` 

The latter is in the site `https://www.shopclues.com/`, but since the subdomain contains `matomo` instead of `analytics`, it's blocked by `://matomo.$from=~matomo.org`.
