### ISSUE TITLE
AdGuard "URL Tracking Protection" filter breaks DuckDuckGo on Firefox: "The page isn’t redirecting properly"

### ISSUE THREAD

**Issue by SlomoDuke** [uBlockOrigin/uAssets#19830]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I use DuckDuckGo as my search engine and I can correctly access the home page, https://duckduckgo.com. 

However, as soon as I hit 'enter' after having entered a search term, let's say "github login" which in turn generates an url like https://duckduckgo.com/?q=github+login&atb=v352-1&ia=web, the browser returns the "The page isn’t redirecting properly" error and I can't proceed any further. 

![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/b22c9350-4284-45e8-899d-c49489f2c046)

After having done some debugging using uBlock Origin logging functionality, it turns out the AdGuard "URL Tracking Protection" filter and in particular the "$removeparam=atb" rule is the culprit: 

![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/66a0136e-6623-4ef8-9098-c463ce7094bc)

If I disable the individual filter in the configuration of the extension, the page redirects properly.
![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/717cccf4-5686-40d4-b0b7-8b47128a1592)

Here is the relevant excerpt from the offending filter:
```
! DuckDuckGo
! https://duckduckgo.github.io/duckduckgo-help-pages/privacy/atb/
||duckduckgo.com^$removeparam=atb                           **<---- cause of my issues**
||duckduckgo.com^$removeparam=vis
||duckduckgo.com^$removeparam=perf_id
||duckduckgo.com^$removeparam=parent_perf_id
```

### URL(s) where the issue occurs.

https://duckduckgo.com/?q=github+login&atb=v352-1&ia=web

### Screenshot(s)

![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/73a4ccee-4a2c-4a16-96b5-8fd83d6f48e9)

### uBO version

Version1.52.0

### Browser name and version

Firefox 117.0.1 - 64-bit for Windows 11

### Settings

Enabled a few filters from the default database, including 

AdGuard URL Tracking Protection

**Comment by SlomoDuke** [comment]
@MasterKia for the record, I actually did search for duplicates and did inspect that other issue.

However, that other issue incorrectly reports that it is NOT a filter issue:
![image](https://github.com/uBlockOrigin/uAssets/assets/145842608/f44313ed-5b3f-47f4-9766-b918ef3b5b59)

But I have proved it actually _is_ a filter issue, so I diligently opened a case of the proper type to report an issue with the filters.

Anyway, let's continue in the other one if it makes things easier for you. I appreciate you looking into this.
