### ISSUE TITLE
affiliate links from Awin.com were blocked by Peter Lowe’s Ad and tracking server list

### ISSUE THREAD

**Issue by Stefanseiner** [uBlockOrigin/uAssets#20550]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://www.awin1.com/cread.php?awinmid=17961&awinaffid=1104681&platform=sl&ued=https://www.manomano.de/p/keiler-keiler-forst-schutzhandschuh-rindnarbenleder-pulsschutz-weich-gefuettert-extra-robust-en388-7266618

### Description

Affiliate links over awin.com affiliate network were blocked by "Peter Lowe’s Ad and tracking server list"

It's the same as links to Amazon e.g. amzn.to would be blocked.

Please remove awin1.com from this list
![Screenshot_005](https://github.com/uBlockOrigin/uAssets/assets/3314379/fd19162a-be92-47f7-b620-43cde6770f29)

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by okiehsch** [comment]
@Stefanseiner it's supposed to work that way uBO warns you that the link you clicked redirects you through an adserver, you then have the choice of proceeding by clicking "fortfahren" or closing the link.

**Comment by Stefanseiner** [comment]
> On what site and **which page** did you encounter this affiliate link?

My own site, for example [this page (all links to "Manomano" are awin affiliate links)](https://mona-stefan.de/index.php?option=com_content&view=article&id=1156&catid=33&Itemid=296), it concerns all urls created by the awin link generator

**Comment by okiehsch** [comment]
> It's the same as links to Amazon e.g. amzn.to would be blocked.

The amazon and aliexpress links work because it's their own affiliate link network not a third-party service.

**Comment by okiehsch** [comment]
> Then we could replace that link with just the [Final destination] to avoid that block page.

Pretty sure the OP, as the site owner, would not be best pleased if we did that. 😉

**Comment by Stefanseiner** [comment]
if tiddly is the only problem then I could leave off shorting the awin links.
But I think it's the "awin1.com" blacklisting which is the problem.

maybe it would help to whitelist "https://www.awin1.com**/cread.php**" because I think it's just part of the affiliate links not of some ordinary ads

**Comment by okiehsch** [comment]
> if tiddly is the only problem then I could leave off shorting the awin links.

You do realize that the way to fix it on our end if you do that would mean that you don't get any montary compensation of a buy?
The way it is right now if your users click "fortfahren" and buy whatever you will get one.

**Comment by Stefanseiner** [comment]
no I don't understand completely.

first: awin links are like this:  https://www.awin1.com/cread.php?awinmid=17961&awinaffid=1104681&platform=sl&ued=https://www.manomano.de/p/keiler-keiler-forst-schutzhandschuh-rindnarbenleder-pulsschutz-weich-gefuettert-extra-robust-en388-7266618

second: the usage of tiddly is not necessary and awin and the monetary compensation work easily without tiddly.

But if I use the long awin urls on the website (just tested it a minute ago) the result is the same, uBlock blocks the awin url

**Comment by okiehsch** [comment]
> no I don't understand completely.

The filter blocking awin links is not "breaking" anything from our point of view.
It works as expected, i.e. it temporarily blocks the redirecting third-party affiliate link and gives the user a choice, either proceed or not. 
Even if the awin links are not using tiddly we would not add afilter allowing it to go through awin.

**Comment by Stefanseiner** [comment]
ok understand, thanks

**Comment by okiehsch** [comment]
> the usage of tiddly is not necessary and awin and the monetary compensation work easily without tiddly.

Just to be clear about what I meant by "no monetary compensation", if you only use awin we could "strip" the affiliate link and on your page only the final destination would appear if you use uBlock, hence no monetary compensation.

**Comment by Stefanseiner** [comment]
thanks but this wouldn't be a helpfull solution

**Comment by okiehsch** [comment]
I agree.
