### ISSUE TITLE
[Firefox Android] Google search result URLs preserve tracking, unless Desktop site mode is used

### ISSUE THREAD

**Issue by ThreeDeeJay** [uBlockOrigin/uAssets#20833]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBlock Origin successfully removes tracking from Google search result URLs for a direct link which allows loading certain links with the associated app, but that only works when enabling Desktop site mode.
This also happens when Enhanced tracking protection is completely disabled.

### A specific URL where the issue occurs.

https://www.google.com/search?q=ublock+origin

### Steps to Reproduce

- Google search anything on Firefox for Android with uBlock Origin. Example: `ublock origin` https://www.google.com/search?q=ublock+origin
- In mobile mode, tap and hold a link to show it still has tracking like this: https://www.google.com/url?sa=AAAAA&source=web&rct=AAAAA&opi=AAAAA&url=https://ublockorigin.com/&ved=AAAAA=AAAAA
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/71472458/37699362-c312-4728-977f-b8af4a1e0384)
- Turn on Desktop site in the menu which refresh the page
- Tap and hold a search result again and this time it should show the direct URL like this: https://ublockorigin.com/
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/71472458/515d8cc4-4bb0-4bcc-b35c-da29c72a75f6)
- Optionally, disable uBlock Origin then refresh to verify that without it, URLs have tracking even in Desktop site mode:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/71472458/f7c0752a-54a1-4cde-80dd-87222cca31fa)

### Expected behavior

uBlock origin should also sanitize/clean search result URLs in mobile (default) mode just like it does with Desktop mode.

### Actual behavior

Google search result URLs preserve their tracking parameters, which can prevent opening URLs in apps that have site associations and instead the links are opened in the same/new browser tab.

### uBO version

1.53.0

### Browser name and version

Firefox 120.0

### Operating System and version

Android 13

**Comment by ThreeDeeJay** [comment]
Ohh, my bad. I thought URL sanitation wasn't directly related to filter lists so I didn't check the uAssets repo.
Anyway, thanks for reopening the original 👍
