### ISSUE TITLE
Proposal to Add New Filter List: Content Blocker - Advanced Tracker and Analytics Blocker

### ISSUE THREAD

**Issue by Prajwal-Koirala** [uBlockOrigin/uAssets#21681]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL(s) where the issue occurs.

https://github.com/complexorganizations/content-blocker

### Description

https://raw.githubusercontent.com/complexorganizations/content-blocker/main/assets/browser.txt

https://github.com/complexorganizations/content-blocker

### Other extensions used

https://github.com/complexorganizations/content-blocker

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by Prajwal-Koirala** [comment]
Hi uBlock Origin team,

I'd like to propose adding my filter list, **Content-Blocker**, which blocks Block anything: Ads, trackers, malware, phishing attempts, you name it. Content Blocker filters your DNS queries, catching unwanted domains before they even load.

You can find it at: [https://raw.githubusercontent.com/complexorganizations/content-blocker/main/assets/browser.txt](https://raw.githubusercontent.com/complexorganizations/content-blocker/main/assets/browser.txt)

https://github.com/complexorganizations/content-blocker

I've tested it thoroughly and it works great on various platforms. Plus, it plays well with your existing lists.

I'm excited to collaborate and integrate it with uBlock Origin. Let me know if you have any questions!

Thanks,
Prajwal Koirala
