### ISSUE TITLE
"Save to playlist" doesn't proceed to checklist selection (when it does just that with uBlock Origin disabed). Chrome. Youtube.com

### ISSUE THREAD

**Issue by conradRz** [uBlockOrigin/uAssets#22114]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
Full XPath /html/body/ytd-app/ytd-popup-container/tp-yt-iron-dropdown/div/ytd-menu-popup-renderer/tp-yt-paper-listbox/ytd-menu-service-item-renderer[3]/tp-yt-paper-item/yt-formatted-string
```

### Description

![image](https://github.com/uBlockOrigin/uAssets/assets/26015206/7f172f33-fea7-48d2-b06a-4ce18f04e206)
 Doesn't allow to add video to a playlist, as it doesn't show the playlist selection with uBlock enabled.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/26015206/a572f064-698f-46c1-9fd3-c206f6223635)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 115474
 cosmetic: 44404
 scriptlet: 20167
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  easylist: 77654-13, 34m
  easyprivacy: 43551-39, 34m
  plowe-0: 3785-1172, 4d.8h.53m
  ublock-badware: 7762-136, 34m
  ublock-filters: 36536-159, 34m
  ublock-privacy: 994-7, 34m
  ublock-quick-fixes: 244-46, 34m
  ublock-unbreak: 2193-32, 34m
  urlhaus-1: 9070-0, 34m
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 23 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 700 ms (selfie)
 maxAssetCacheWait: 351 ms
popupPanel:
 blocked: 45
 network:
  youtube.com: 1
  doubleclick.net: 4
  google.com: 40
 extended:
  ##tp-yt-paper-dialog.ytd-popup-container.style-scope
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?([A-Z]"\}|"…
  ##+js(trusted-replace-xhr-response, /"adPlacements.*?("adSlots"|…
  ##+js(trusted-replace-fetch-response, /"adPlacements.*?([A-Z]"\}…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  #@#+js(set-constant, ytInitialPlayerResponse.playerAds, undefine…
  #@#+js(set-constant, ytInitialPlayerResponse.adPlacements, undef…
  #@#+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  #@#+js(set-constant, playerResponse.adPlacements, undefined)

```
</details>
