### ISSUE TITLE
Exception filter allowing Reddit tracking found in uBlock filters?

### ISSUE THREAD

**Issue by MPeti1** [uBlockOrigin/uAssets#8529]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`reddit.com`

### Describe the issue

There is an exception filter for `https://www.redditstatic.com/desktop2x/js/xads.js` in the `uBlock filters` filterlist.
This is a problem, because even after adding a blocking static filter for this script (without the `important` addition) the script won't be blocked.

The exception filter: `@@||redditstatic.com^*/xads.js$script,domain=reddit.com`

 

### Screenshot(s)

Example of when the rule overrules my blocking filter:
![image](https://user-images.githubusercontent.com/9215491/106669755-6a789600-65ac-11eb-9ab7-602170d94623.png)

My blocking filter in the `My filters` tab of the addon settings page:
![image](https://user-images.githubusercontent.com/9215491/106669834-8b40eb80-65ac-11eb-9e3b-3ad93fc530cd.png)

The exception rule in the built-in uBlock filter list:
![image](https://user-images.githubusercontent.com/9215491/106669915-add30480-65ac-11eb-8fe8-d2f4d5d3eb52.png)

### Versions

- Browser/version: Firefox 85.0
- uBlock Origin version: v1.33.0

### Settings

<details>
<summary>Main settings</summary>
![image](https://user-images.githubusercontent.com/9215491/106670116-e96dce80-65ac-11eb-907b-1652a5ecd690.png)
</details>
<details>
<summary>Hidden settings</summary>

allowGenericProceduralFilters false
assetFetchTimeout 30
autoCommentFilterTemplate {{date}} {{origin}}
autoUpdateAssetFetchPeriod 120
autoUpdateDelayAfterLaunch 180
autoUpdatePeriod 4
benchmarkDatasetURL unset
blockingProfiles 11111/#F00 11010/#C0F 11001/#00F 00001
cacheStorageAPI unset
cacheStorageCompression true
cacheControlForFirefox1376932 no-cache, no-store, must-revalidate
cloudStorageCompression true
cnameIgnoreList unset
cnameIgnore1stParty true
cnameIgnoreExceptions true
cnameIgnoreRootDocument true
cnameMaxTTL 120
cnameReplayFullURL false
cnameUncloak true
cnameUncloakProxied false
consoleLogLevel unset
debugScriptlets false
debugScriptletInjector false
disableWebAssembly false
extensionUpdateForceReload false
filterAuthorMode false
filterOnHeaders false
ignoreRedirectFilters false
ignoreScriptInjectFilters false
loggerPopupType popup
manualUpdateAssetFetchPeriod 500
popupFontSize unset
popupPanelDisabledSections 0
popupPanelLockedSections 0
popupPanelHeightMode 0
requestJournalProcessPeriod 1000
selfieAfter 3
strictBlockingBypassDuration 120
suspendTabsUntilReady unset
uiPopupConfig undocumented
uiFlavor unset
uiStyles unset
uiTheme unset
updateAssetBypassBrowserCache false
userResourcesLocation unset

</details>

### Notes

Question mark in the title because I'm not exactly sure that @@ is the exception filter, but according to [this](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-network-filtering) and my screenshot it probably is.

As I mentioned, adding `,important` to my filter rule makes it working, but wanted to ask about the purpose of the exception filter because as of now I don't see it's benefit.

**Comment by okiehsch** [comment]
> wanted to ask about the purpose of the exception filter because as of now I don't see it's benefit.

![image](https://user-images.githubusercontent.com/16838044/106677197-9e59b880-65b8-11eb-9c90-918839389e6e.png)

The purpose stated is reddit anti adblock tracking. The site checks if that request is blocked and if it is it assumes the user has an adblocker enabled.
The sole purpose of that script is to check if you use an adblocker or not.

**Comment by MPeti1** [comment]
Thank you!
But what problem does it cause if I block this script? I have it blocked since yesterday, and so far I haven't seen even a warning about using an adblocker

**Comment by mapx-** [comment]
Maybe if they get that bait blocked will try to push some other ads

**Comment by okiehsch** [comment]
> But what problem does it cause if I block this script?

There is no "problem" if you block it. 
What is the "problem" if you don't block it?

**Comment by MPeti1** [comment]
Actually I was just wathcing the logger for anything unnecessary, like ad scripts and such, and since the name of this implies that this is an ad script (yes, I've checked since and I see that it practically doesn't do anything) I wanted to block it, and then I was just surprised that there was an exception filter for it. Now I'm not sure anymore if I really want to block it :D

Could I ask how do you know that it's purpose is anti-adblock tracking? Just asking out of curiosity
