### ISSUE TITLE
[Breakage] Tweakers.net sidebar ("tracker") with forum, news, blogposts, ... invisible

### ISSUE THREAD

**Issue by canihavesomecoffee** [uBlockOrigin/uAssets#8986]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
    - [x] disabling uBlock Origin
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://tweakers.net/`

### Describe the issue

Since somewhere this afternoon the sidebar on Tweakers is no longer visible. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7365586/116738144-5ea54000-a9f2-11eb-9634-102ca05fc17d.png)

(note that I use their custom CSS feature, but I ruled that out by disabling it, the sidebar still remained empty)

### Versions

- Browser/version: Firefox 88
- uBlock Origin version: v1.35.0

### Settings

Default settings

### Notes

Disabling uBlock Origin fixes it, making me suspect the recent commit (208ac4cc69a5e29caceb22330cdee2d3e70afa63) is causing the issue. Disabling "uBlock filters" out of the rulesets also makes the tracker visible.

**Comment by uBlock-user** [comment]
Add  `tweakers.net#@#+js(aopr, document.head.appendChild)` and report back

**Comment by canihavesomecoffee** [comment]
Setting that as a custom filter and disabling the uBlock filters brings it back. Since I don't have ads (have a subscription) I can't test out if that's effective at blocking special ads though.

**Comment by uBlock-user** [comment]
>  disabling the uBlock filters

Do not do this, subscribe back and test again.

**Comment by canihavesomecoffee** [comment]
> > disabling the uBlock filters
> 
> Do not do this, subscribe back and test again.

Wasn't aware that custom filters take precedence over lists :)

Setting your suggestion as custom filter + enabled uBlock filter list is still working as intended. Without custom filter it's missing.

**Comment by crisp-tweakers** [comment]
This is now the third or fourth time that uBlock is breaking legitimate functionality on our website in their quest to block AdDefend's (privacy friendly and tracking free) banners. We are not very happy about this.

**Comment by uBlock-user** [comment]
> This is now the third or fourth time that uBlock is breaking legitimate functionality on our website in their quest to block AdDefend's (privacy friendly and tracking free) banners. We are not very happy about this.

Do not circumvent our filters either and stop fighting back, your actions are the reasons this happens in the first place.

**Comment by mapx-** [comment]
@canihavesomecoffee Where exactly is that sidebar ? is it visible only having an account ?

**Comment by crisp-tweakers** [comment]
> Do not circumvent our filters either and stop fighting back, your actions are the reasons this happens in the first place.
Excuse me? It is not like we just started using `document.head.appendChild` yesterday to dynamically add functionality to our pages. When you try to block things with such generic rules chances high are you are also breaking legitimate functionality. Our visitors come to us first with bugreports, but we are sure to pin the blame on you which makes uBlock look bad.

I'm fine with your battle against AdDefend, but I am constantly getting caught in the middle of this trying to figure out these reported problems while we didn't change a thing. We are not responsible for the AdDefend code itself.

**Comment by mapx-** [comment]
> We are not responsible for the AdDefend code itself.

You put together addefend crap other site code, you know that => you break your own site on purpose.

**Comment by canihavesomecoffee** [comment]
@mapx- 

By default it's folded in:
![Screenshot from 2021-04-30 21-15-03](https://user-images.githubusercontent.com/7365586/116743515-9313fe80-a9e8-11eb-8857-becb82565343.png)

And when unfolded:
![Screenshot from 2021-04-30 21-16-10](https://user-images.githubusercontent.com/7365586/116743513-91e2d180-a9e8-11eb-9b4c-120682e227b1.png)

I have some small CSS fixes applied to permanently show it though.

**Comment by mapx-** [comment]
@canihavesomecoffee  thanks, now I got it
